import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import getCurrentUser from "./actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const currentUser = await getCurrentUser();
	console.log(currentUser);

	return (
		<html lang="en">
			<body className={`dark bg-slate-800 ${inter.className}`}>{children}</body>
		</html>
	);
}
